### ISSUE TITLE
LDAP automated configuration

### ISSUE THREAD

**Issue by GaetanLongree** [docker-library/owncloud#100]
Is it possible to preconfigure OwnCloud containers at run time?
Either through a static configuration file passed to the container, or through a Dockerfile so that LDAP server information could be passed using arguments at run time.

**Comment by wglambert** [comment]
From [Owncloud docs](https://doc.owncloud.org/server/9.0/admin_manual/configuration_user/user_auth_ldap.html) it seems that there isn't any central config file that I can see. I'm sure there's a way to preconfigure ldap but this isn't a feature we're looking to support.
