### ISSUE TITLE
would it make sense to you upgrading this image to php 7.2?

### ISSUE THREAD

**Issue by encodeering** [docker-library/owncloud#106]
Hey,

I've read your deprecation notice and I am just wondering if you think it would be beneficial to still upgrade this image to php 7.2 before you close this repository, as it seems to be supported rom their side now.

https://doc.owncloud.org/server/latest/admin_manual/installation/source_installation.html#prerequisites

They follow a different construction process, which makes this image preferable, at least to me.

Kind regards

**Comment by yosifkit** [comment]
Sounds good! see #107.

**Comment by encodeering** [comment]
Awesome, thanks a lot.
