### ISSUE TITLE
9.1 is EOL

### ISSUE THREAD

**Issue by J0WI** [docker-library/owncloud#110]
https://owncloud.org/news/goodbye-owncloud-9-1-welcome-owncloud-lts/

**Comment by tianon** [comment]
This is good to know, but this entire repository/image will be EOL and archived after Dec 31st, so IMO this isn't really worth taking action on here.

**Comment by yosifkit** [comment]
Closing given that this image will no longer be updated.

> This image has been deprecated in favor of the [official `owncloud/server` image](https://hub.docker.com/r/owncloud/server/) provided, maintained, and supported by [ownCloud upstream](https://owncloud.org/download/#owncloud-server-docker). The images found here will receive no further updates after 2018-12-31 (Dec 31, 2018). Please adjust your usage accordingly.
>
> \- https://github.com/docker-library/owncloud/tree/d815707323e2dce4696a1f7b1639f86fc6bf8b8a#deprecated
