### ISSUE TITLE
Add alias

### ISSUE THREAD

**Issue by sils** [docker-library/owncloud#17]
Would be nice to be able to pass an environment variable to get the owncloud accessible via `localhost/some_alias`. This can be easily done with a configuration file like https://github.com/sils1297/docker-centos-owncloud/blob/master/template/owncloud.conf and a simple sed instruction in the startup script like https://github.com/sils1297/docker-centos-owncloud/blob/master/startup.sh#L45 .

**Comment by yosifkit** [comment]
I'm not sure I see this actually solving anything.  When owncloud is running with `-p 80:80` nothing else would be available on `localhost` anyway (well, on port 80).  You could run it as `-p 8080:80` and then it would be available on `localhost:8080` or even run it without a `-p` and either hit the container ip, use an `ngninx` or `haproxy` container to route requests, or use something like `rawdns`.
