### ISSUE TITLE
Add apc configuration

### ISSUE THREAD

**Issue by sils** [docker-library/owncloud#18]
Could help boost performance a bit. @cw1 did that for our image from some sources in the internet I don't recall anymore which resulted in: https://github.com/sils1297/docker-centos-owncloud/blob/master/template/apc.ini

Can also be mande configurable by environment variables in addition.

**Comment by sils** [comment]
https://forum.owncloud.org/viewtopic.php?f=8&t=10692 is also probably worth a look

**Comment by lazyfrosch** [comment]
Please see #16.

You should be able to finetune via .htaccess, right?

**Comment by lazyfrosch** [comment]
Oh and you'd have to activate APCu as described in owncloud config

**Comment by pierreozoux** [comment]
I think it is now solved by https://github.com/docker-library/owncloud/commit/e129f3ea6a65c9273ef206a23a68e384280c6793

@sils1297 can you confirm and close please?

**Comment by tianon** [comment]
Please feel free to open a new issue if more problems are discovered. :+1:

**Comment by sils** [comment]
Sorry, this got lost. - Thanks!
