### ISSUE TITLE
News App doesn't work

### ISSUE THREAD

**Issue by HeaDBanGer84** [docker-library/owncloud#20]
can you please install requirements for News App. It is an official Owncloud-App and would be really useful:
# Dependencies for News-App
- ownCloud >= 8.1
- libxml >= 2.7.8 (2.9 recommended)
- php-curl
- iconv
- SimpleXML
- PHP >= 5.5

get full information: https://github.com/owncloud/news#readme

**Comment by yosifkit** [comment]
Since the installation of this addon app would be within the volume, I think it could make sense to also enable these php modules on the 8.1 image.  That way a user only needs to mount their owncloud directory with the news app in the `apps/` directory.  Are these common modules that would be needed for the commonly used `apps` for owncloud?

**Comment by HeaDBanGer84** [comment]
This is exactly what i meant. Please enable the dependencies of the official Apps (Contacts, Calendar, News..., most of them work anyway) the Installation can be done easily by on each deployment. But at least I'm not willing to build my own image just because of this few additional dependencies.
You can find the official Apps in their github: https://github.com/owncloud?page=2
I have tested:
- Tasks (works)
- Calendar (works)
- Contacts (works)
- Mail (works)
- ownNote (experimenatl) (works)
- direct Menu (experimental) (works)
- News (doesn't work: can't load any page after installing, have to delete Directory to fix)

**Comment by yosifkit** [comment]
Would you be willing to do a PR updating the [apt install lines](https://github.com/docker-library/mysql/blob/fa632dc9b955f58650fc2ad3e1bb971b5e92816f/5.6/docker-entrypoint.sh#L32-L38) to add any necessary system libraries and then update the [php-ext-install lines](https://github.com/docker-library/owncloud/blob/9407be83adf4886035585f99ecab12661fd05cf5/8.1/Dockerfile#L20-L21) to add the new modules?

**Comment by HeaDBanGer84** [comment]
I think its not necessary. I have tested and found out that you you just have to change in DOCKERFILE is the `FROM` line to

```
 FROM php:5.5-apache
```

After that change my tests works just fine.

To do the needed cron job add the following line to the host crontab or create a similar systemd.timer

```
*/15 *  *  *  * /usr/bin/docker exec -u www-data <your-owncloud-container-name/id> /usr/local/bin/php /var/www/html/cron.php > /dev/null 2>&1
```

thats all

**Comment by yosifkit** [comment]
Oh, is that all?  :+1:

**Comment by HeaDBanGer84** [comment]
Seems to be, I started Testing today with a fresh clone just changed that line and everything works (the rest of the dependencies you already install). I think the cron part is not your problem and should not be part of the image, but a little hint in the documentation would be nice.
