### ISSUE TITLE
Describe the mount points for data and config directories

### ISSUE THREAD

**Issue by asridharan** [docker-library/owncloud#22]
I can always bash into the image and look up the data and config folders, and mount them on local volumes for persistency. But it would be better if we can describe them in the documentation.

**Comment by Alexander-Barth** [comment]
I think that this is a very good suggestion. I would also place the data outside the docker container so that I can upgrade owncloud more easily.

**Comment by miton18** [comment]
have your got path of data, to add in "docker run -v" ?

**Comment by lazyfrosch** [comment]
I'm wondering what you exactly wanna know, and how we should document it... ?

**Comment by Alexander-Barth** [comment]
For instance, it would be good to document (if not already done, but I did not find this info) that the user data is stored in /var/www/html/data. So to save the data outside the container, one need to run:

docker run -d  -v /some/path/that/I/backup:/var/www/html/data --name owncloud-8.2.1 owncloud:latest

For the configuration, I would be good to document that they are in /var/www/html/config/.
Those paths are not difficult to find out, but to document it will lower the barrier for some.

If you are wondering how to document it, you may have a look here:
https://github.com/l3iggs/docker-owncloud/wiki/Store-your-data-outside-of-the-container

**Comment by lazyfrosch** [comment]
Ah I see, well there is only one volume `/var/www/html` which you should persist completely, because it contains config, and installed plugins.

We should add a block to the docs.

To update owncloud itself you have to remove `version.php`, so the entrypoint will update the PHP code.

**Comment by tianon** [comment]
Doesn't owncloud have a self-update mechanism too that can be invoked via
the web UI similar to wordpress?

**Comment by pierreozoux** [comment]
@lazyfrosch I personally prefer fine grained :)
https://github.com/indiehosters/ownCloud/blob/master/docker-compose.yml#L14-L16

But if you use the full folder `/var/www/html`, then, yes @tianon, you can use the webUI tool (if you have the right permissions).
I wouldn`t recommend it as you don't update debian/php though, and would miss this kind of [subtilities](https://github.com/docker-library/owncloud/commit/a047a61dc87a72b5b055e502bcd3636dfb1a0ce9).

**Comment by tianon** [comment]
:+1: sounds like we could use some better docs :smile:

**Comment by lazyfrosch** [comment]
Will docker-library/docs#436 fit your needs? :)

**Comment by nterray** [comment]
:+1: This addendum in the docs would be great!
