### ISSUE TITLE
LDAP user and group backend doesn't work

### ISSUE THREAD

**Issue by celk** [docker-library/owncloud#24]
I can't install the LDAP backend app.

`This app cannot be installed because the following dependencies are not fulfilled:
The library ldap is not available.`

Installing the php5-ldap package doesn't solve the issue.

**Comment by yosifkit** [comment]
Yeah, the installed php is not from the debian repos, but the source directly from php. You should be able to use the `docker-php-ext-install` script to install php extensions (https://github.com/docker-library/docs/tree/5aedb893669ed6947a77124762febb9b40d67cbf/php#how-to-install-more-php-extensions).

**Comment by pierreozoux** [comment]
See https://github.com/docker-library/owncloud/pull/29
