### ISSUE TITLE
php-fpm version?

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/owncloud#25]
Hi,

I was working on an [owncloud image](https://github.com/indiehosters/ownCloud/tree/master) to PR from [owncloud](https://github.com/owncloud/core/issues/10615#issuecomment-123753237) but you were faster ;)

Anyway, I noticed that it is using apache and you don't offer a php-fpm alternative (as for wordpress for instance).

Would you be interested in me PRing for a php-fpm version?

Best!

Pierre

**Comment by yosifkit** [comment]
That would be great!

**Comment by pierreozoux** [comment]
How do we organise the folder?

Like wordpress with 2 folders (apache and fpm).
Or do you prefer a new folder 8.1-fpm?

**Comment by yosifkit** [comment]
Let's just put an `fpm` folder inside each of the version folders (`8.1/fmp/Dockerfile`).  We'll also need to modify `update.sh` and `generate-stackbrew-library.sh` to handle the new fpm Dockerfiles. Let me know if you need anything else. Thanks for the help!

**Comment by almereyda** [comment]
This exists in
- https://github.com/owncloud/administration/blob/master/docker/images/ubuntu/oc-nginx/Dockerfile
- https://github.com/jchaney/owncloud/blob/master/Dockerfile
