### ISSUE TITLE
Activate PHP-Opcacheing

### ISSUE THREAD

**Issue by ghost** [docker-library/owncloud#26]
Hello,

could you add `opcache` to the `docker-php-ext-install` line? PHP 5.6 comes with the zend opcache bundled, all you need to do is to add this line. I could also fork an make a pull request if you like.

Kind regards
Florian

**Comment by lazyfrosch** [comment]
owncloud is recommending APCu, doesn't this also cache compiled PHP code?

https://owncloud.org/blog/making-owncloud-faster-through-caching/

**Comment by ghost** [comment]
TL;DR: we need both, the PHP `opcache` and APCu

These are two differnt types of caching. `opcache` as i stated above is a PHP Opcache, it caches the compiled version of the PHP script. APCu is a user cache (Key-Value Store), which is used by owncloud to cache expensive database queries. APCu is APC without the PHP Opcache, afaik APC wont work with PHP 5.5 an up anymore.

**Comment by yosifkit** [comment]
APCu is [installed](https://github.com/docker-library/owncloud/blob/master/8.1/Dockerfile#L24-L25). Only `8.1` is using PHP 5.6, would it help to update the other versions of owncloud to use 5.6 so that they also can have `opcache` enabled?  I would greatly enjoy a PR, thanks for the help!
