### ISSUE TITLE
Warning in admin panel using current latest docker image

### ISSUE THREAD

**Issue by beingalink** [docker-library/owncloud#32]
Seems like I posted this issue initially at the wrong place ([owncloud/administration](https://github.com/owncloud/administration/issues/55)):

I'm using the official dockerfile tagged "8.1.3, 8.1, 8, latest (8.1/Dockerfile)".

In the admin panel I get following warning:

```
Your data directory and your files are probably accessible from the Internet. The .htaccess file is not
working. We strongly suggest that you configure your web server in a way that the data directory is no
longer accessible or you move the data directory outside the web server document root.
```

This seems to be a false warning since I tested to access my files via "http://example.com/data/$username/files/known_file.txt" which was blocked as it should.

Any help is welcome.

**Comment by TheLink** [comment]
Seems like there was a file named htaccesstest.txt in the data folder. After removing this file, the warning disappears. I have no idea how this file got there. Anyway, case closed.
