### ISSUE TITLE
problem with owncloud:8.1.3-fpm

### ISSUE THREAD

**Issue by ghost** [docker-library/owncloud#33]
```
docker run -d -p 80:80 owncloud:8.1.3-fpm
```

In browser on `http://localhost` there is `ERR_CONNECTION_RESET` error.
Can you help to fix this?

For example, this dont work too.

```
docker run -d -p 8099:80 owncloud:8.1.3-fpm
```

**Comment by ghost** [comment]
And, in owncloud8.2 you forget to make entrypoint script executable - it brokes the build.

And here after fixing in browser the same error.

**Comment by tianon** [comment]
Are you running on a Mac or Windows box using docker-machine?  If so,
you'll have to hit the VM IP address instead of localhost ("docker-machine
ip default", replacing default with your machine name).

I just double-checked the executability of the "docker-entrypoint.sh"
scripts in the 8.2 folders and they are "+x", so I'm a little puzzled
what's going on there.

**Comment by ghost** [comment]
I use gnu/linux.

About entrypoint bash script - this was my mistake, I had used wget instead of git. 

`netstat -lntu`:

```
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:139             0.0.0.0:*               LISTEN     
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:631           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:445             0.0.0.0:*               LISTEN     
tcp6       0      0 :::139                  :::*                    LISTEN     
tcp6       0      0 :::80                   :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:631                 :::*                    LISTEN     
tcp6       0      0 :::445                  :::*                    LISTEN     
udp        0      0 0.0.0.0:5353            0.0.0.0:*                          
udp        0      0 127.0.1.1:53            0.0.0.0:*                          
udp        0      0 0.0.0.0:68              0.0.0.0:*                          
udp        0      0 192.168.1.255:137       0.0.0.0:*                          
udp        0      0 192.168.1.93:137        0.0.0.0:*                          
udp        0      0 172.17.255.255:137      0.0.0.0:*                          
udp        0      0 172.17.42.1:137         0.0.0.0:*                          
udp        0      0 192.168.1.255:137       0.0.0.0:*                          
udp        0      0 192.168.1.4:137         0.0.0.0:*                          
udp        0      0 0.0.0.0:137             0.0.0.0:*                          
udp        0      0 192.168.1.255:138       0.0.0.0:*                          
udp        0      0 192.168.1.93:138        0.0.0.0:*                          
udp        0      0 172.17.255.255:138      0.0.0.0:*                          
udp        0      0 172.17.42.1:138         0.0.0.0:*                          
udp        0      0 192.168.1.255:138       0.0.0.0:*                          
udp        0      0 192.168.1.4:138         0.0.0.0:*                          
udp        0      0 0.0.0.0:138             0.0.0.0:*                          
udp        0      0 0.0.0.0:45302           0.0.0.0:*                          
udp        0      0 0.0.0.0:14791           0.0.0.0:*                          
udp        0      0 0.0.0.0:631             0.0.0.0:*                          
udp6       0      0 :::37802                :::*                               
udp6       0      0 :::5353                 :::*                               
udp6       0      0 :::55325                :::*  
```

As I understand, 80 port is free.

**Comment by yosifkit** [comment]
With the fpm version you'll need something that speaks the FastCGI protocol to talk to it, like nginx.  @md5 wrote a pretty good gist about setting it up with the wordpress image: https://gist.github.com/md5/d9206eacb5a0ff5d6be0.

**Comment by ghost** [comment]
As I understand, regardless docker developer recommendation of using one process-per-container methodology, many docker apps developers execute many processes in one container, like this.

This image include unknown for me webserver and predinstalled php-fpm.
And in manual to this repo is written that 

```
docker run -d -p 80:80 owncloud:8.1.3-fpm
```

enough.

**Comment by tianon** [comment]
Right, for running a FastCGI server, which then has to be connected to
through something like Nginx which speaks the FastCGI protocol (browsers do
not).  If you want to run something you can connect to directly from a web
browser, you'll have to use the Apache variant instead.

**Comment by pierreozoux** [comment]
Arg, not fast enough :)
@a93ushakov yes, you need a web server in front.
You can find a docker-compose here: https://github.com/indiehosters/ownCloud (if you need help, please open an issue, I'd be really happy to help you!)

This is part of an ongoing issue: https://github.com/docker-library/docs/issues/238
(I really would like to help on this also, but time is missing.)

@a93ushakov can you close the issue if we answer your question? Thanks!

**Comment by ghost** [comment]
I try to `compose up`, in console I see db stats (why they are shown? it's uncomfortable) and no way to open owncloud in browser - where exposed ports are listed?

**Comment by pierreozoux** [comment]
Please open this in the rigth repo.

PS: I updated the doc, is it clearer? (By default, not exposing port on the host). About the stats, be more precise, what do you mean db stats?

Thanks :)

**Comment by ghost** [comment]
![screenshot from 2015-10-22 00 38 54](https://cloud.githubusercontent.com/assets/13286493/10650977/540d577e-7855-11e5-8879-c4d54b7622f1.png)

I edit `docker-compose.yml`, all works now, thank you.
P.S. Maybe 

```
  ports:
    - "443:443"
    - "80:80"
```

instead of

```
  - ports:
    - "443:443"
    - "80:80"
```

?

**Comment by pierreozoux** [comment]
Arf, I need to sleep! Thanks for your quick feedback and happy it is serving you :) (Please put ssl :) )
About the db stats, it is the good practice of Docker, log to stdout. And the mysql container is following this.
