### ISSUE TITLE
HowTo use owncloud:fpm?

### ISSUE THREAD

**Issue by zyrill** [docker-library/owncloud#34]
I have no idea how to use the container labeled "owncloud:fpm" and google turns up a total of 7 hits on "owncloud:fpm" - is it possible to get some more information on how to use it?

**Comment by pierreozoux** [comment]
@zyrill  you need a web server in front.
You can find a docker-compose here: https://github.com/indiehosters/ownCloud (if you need help, please open an issue, I'd be really happy to help you!)

This is part of an ongoing issue: docker-library/docs#238

@zyrill can you close the issue if we answer your question? Thanks!

**Comment by zyrill** [comment]
Thanks for the tips, I'll have a look this evening and open another issue with the docker-compose if I can't find a way to make it work. Thanks a lot!
