### ISSUE TITLE
Tips or tricks to using Mariadb/Mysql with OC?

### ISSUE THREAD

**Issue by vfulco** [docker-library/owncloud#35]
I have tried everything in the book to use mariadb/mysql from the installation page with the database, nginx-proxy (forcing to https:), redis and owncloud containerized and running ( while using persistent volumes).  The error message is either connection refused or access denied for foo@localhost or foo@127.0.0.1.  I've verified the user exists and has all privileges.  Also attempted...

1) starting with sqlite on a brand new account converting to mysql...during conversion access denied to database previously created within mysql

2) building and verifying the user, password, database and IP address in mysql first then trying to access by OC directly.

3) setting all variables to one word and trying it

4) verified user was set to 127.0.0.1 but also tried localhost and other 172.xx.xx.xx IP addresses

5) have tried mysql 5.5, mariadb:latest, bitanmi's flavor of mariadb, etc.

I don't want to install the database directly to my VPS although some have had success.  No selinux on this server which is ubuntu 15.04.

TIA.

**Comment by pierreozoux** [comment]
Where is your database? same container? If you are using a linked container, you should not try on localhost, but give the hostname of the database.

There is a working setup at this address: https://github.com/indiehosters/ownCloud (I think you can just replace mysql with mariadb). Can you try it out? I think your error is on the localhost.

(if it fixes your problem, please close the issue)

**Comment by vfulco** [comment]
Separate container on the same VPS, your suggestion to try the host IP is a good one but doesn't work.  I am exposing port "3306" in a docker compose file.  Also tried database user name "root" and no  password which didn't work.  Going to try the docker0 IP next.

Addendum: docker0 IP doesn't work either.

**Comment by yosifkit** [comment]
If you have a docker-compose file similar to the below, then in the setup of owncloud you would put "dnsaliasfordb" for the address of the sql server.

``` yaml
app:
  image: owncloud
  links:
    - db:dnsaliasfordb
db:
  image: mariadb
# env stuff....
```

**Comment by vfulco** [comment]
Sorry, could you clarify please?  This is the first mention I have seen of a "- db:dnsaliasfordb" in tens of tens of websites I have read. Most guide to using standard docker container links from db to oc.  I have a host IP, a docker0 IP, "localhost" and localhost represented in IP. I've also seen some logs referring to 172.xx.xx.xx addresses but haven't been able to track down their reference.  TIA.

**Comment by vfulco** [comment]
Ultimately I switched to postgresql and am up and running.  The latest version fixed the "incorrect version" bug which was plaguing me a few weeks back.  Thanks all.
