### ISSUE TITLE
Upgrading existing image

### ISSUE THREAD

**Issue by MihaMarkic** [docker-library/owncloud#37]
Hi guys,

I wonder how the upgrade is handled. Let's say I'm running owncloud image 7.0 and I want to upgrade to the latest. How should one handle that?
I assume a volume container should be used for data but will new image over the data from older image able to handle the (if necessary) upgrade?

**Comment by yosifkit** [comment]
There is nothing we have added to the image to handle upgrading. On startup, the script only copies in the owncloud files if `version.php` does not exist (https://github.com/docker-library/owncloud/blob/974d72da5a196af18a51b586bff84487fd92251e/8.2/apache/docker-entrypoint.sh#L4-L7), so killing your first container and starting a new version with the same volume would not change the owncloud files.

I would assume that the regular upgrade process would work: https://doc.owncloud.org/server/8.0/admin_manual/maintenance/upgrade.html.

**Comment by pierreozoux** [comment]
I noticed that self upgrading from the webUI failed:
https://github.com/indiehosters/ownCloud/issues/4

I personally prefer to mount just the necessary data (like just `apps`, `data` and `config` folder), and then I just `docker pull` and `docker-compose stop, rm, up`.
Then, before, I was going to the webUI to start the upgrade of the database, but the thing is that it fails!
https://github.com/owncloud/core/issues/17823

I found a "nice" way of handling that, I run this:
https://github.com/indiehosters/ownCloud/issues/3

I post this here for people that might be interested to upgrade on an unattended way.

But I'd like to know if you are interested in a PR that we could put this in the docker-entrypoint.
I don't know what is the 'policy' for upgrade of official docker images, but I believe it would be nice :)

Let me know!

**Comment by toplac** [comment]
Any news on this? Currently i am using version 8-apache and i would like to upgrade to version 9-apache. 

Data is stored inside a volume, and mysql is running in  a second container. Is it enough to stop the container, delete the file verison.php, pull in the newest version and start up everything again?

**Comment by pierreozoux** [comment]
I just upgraded, it was almost "smooth".

I have my own setup on docker-compose:
https://github.com/indiehosters/ownCloud

I replaced this line: https://github.com/indiehosters/ownCloud/blob/master/docker-compose.yml#L10

I pulled and restarted, and everything was almost fine.
I have some notes of what needed to be done:
https://github.com/indiehosters/ownCloud/issues/3#issuecomment-194453876

**Comment by vbauchart** [comment]
I also don't like the way this image is build, because all code is in a volume instead of the image itself !

Take a look at this Nextcloud image https://github.com/chrootLogin/docker-nextcloud/blob/master/Dockerfile to see how to build a portable and upgradable image

**Comment by pierreozoux** [comment]
@vbauchart this is free software, please use what you feel comfortable with :)

In the mean time, we are discussing this also in Nextcloud:
https://github.com/nextcloud/docker/pull/23

**Comment by tianon** [comment]
Just tried the self-updater, and it appears the problem with it is a simple fix:

```
sh: 1: unzip: not found
```

:sweat_smile:
