### ISSUE TITLE
Shutdown after creating account

### ISSUE THREAD

**Issue by TimDowker** [docker-library/owncloud#39]
Created new container using Latest and went thru the web setup, creating an account.  Get this error now.

[Fri Dec 18 02:27:28.779221 2015] [mpm_prefork:notice] [pid 1] AH00170: caught SIGWINCH, shutting down gracefully

Any thoughts?

**Comment by tianon** [comment]
Did you start the container with "-it" and then resize the terminal you're
running it in? (that's usually where signals like "SIGWINCH" come from)

**Comment by TimDowker** [comment]
Thank you for the suggestion.  No I did not run it with "-it" as I am trying to run it on my Synology box.

Any ideas how I would do that?

Thanks again for the help.

**Comment by tianon** [comment]
I don't know anything about Synology, sorry -- do they have some kind of web UI you're launching this container from, or are you doing a `docker run` command manually on the box in question?
