### ISSUE TITLE
A lot of errors in error log about loaded 'xmlwriter' module

### ISSUE THREAD

**Issue by outcoldman** [docker-library/owncloud#4]
I see a lot of error messages, like

```
Error   PHP Module 'xmlwriter' already loaded at Unknown#0  2015-07-28T18:45:03+00:00
Error   PHP Module 'xmlwriter' already loaded at Unknown#0
```

My guess that this module is specified multiple times somewhere

**Comment by tianon** [comment]
I _think_ this was likely https://github.com/docker-library/php/issues/102, fixed via https://github.com/docker-library/php/pull/122.  Can you still replicate with an updated image that includes that fix?
