### ISSUE TITLE
Upgrade PHP to PHP 7

### ISSUE THREAD

**Issue by mouhamed** [docker-library/owncloud#41]
Hello guys,

Since PHP 7 is officially released and own cloud claims officially latest version (8.2) is compatible, why not upgrade the source docker image to PHP 7 ?

Thanks,
Mouhamed

**Comment by beingalink** [comment]
I'd also like to see an owncloud:fpm image based on php 7. I think this would be perfect for testing compatibility before shipping it.

**Comment by lazyfrosch** [comment]
How about one of you guys testing the image with a `FROM php:7` and give a PR?

**Comment by tianon** [comment]
Do plugins have broad support for it yet?  I know over in Wordpress land, compatibility is still a little bit rocky.

**Comment by LukasReschke** [comment]
This will break stuff such as the calendar and contacts app. I'd advocate to wait until we release ownCloud 9 in March (or so) as this version has some more compatibility fixes. Base ownCloud installation should work fine though.

**Comment by mouhamed** [comment]
owncloud 9 is released now and is compatible with PHP 7.

**Comment by sbani** [comment]
I upgraded the image to `php7-fpm` but can't install memcache(d). Redis and apcu works fine.

Not using php7-fpm is another possibility. I could create an alpine version or another one based on package manager installations.

Please let me know  if one of you is able to install/compile memcached for php7 based on the `php7-fpm` docker image.

**Comment by beingalink** [comment]
@sbani I'm using following install routine in my dockerfile for the PECL extensions:

```
# PECL extensions
RUN pecl install APCu
RUN git clone -b php7 https://github.com/phpredis/phpredis.git \
        && cd phpredis \
        && phpize && ./configure && make && make install && cd .. && rm -rf phpredis
RUN git clone -b php7 https://github.com/php-memcached-dev/php-memcached.git \
        && cd php-memcached \
        && phpize && ./configure && make && make install && cd .. && rm -rf php-memcached
RUN docker-php-ext-enable apcu redis memcached
```

This seems to work for me.

**Comment by sbani** [comment]
Thanks @beingalink. As you can see I'm doing nearly the same but without a git checkout (I download instead).

But works fine

**Comment by tianon** [comment]
Fixed via https://github.com/docker-library/owncloud/pull/89. :+1:
