### ISSUE TITLE
Webdav doesn't work

### ISSUE THREAD

**Issue by thomasreus** [docker-library/owncloud#42]
I try to configure an owncloud container (latest) behind an nginx reverse proxy. Using the browser works fine but if I want to sync my calendars via webdav (thunderbird / lightning), I got the following error in /var/www/html/data/owncloud.log:

{"reqId":"oq32Qo79zWIxlrZkpbR+","remoteAddr":"192.168.178.36","app":"caldav","message":"Exception: {\"Message\":\"Requested uri (\\/owncloud\\/remote.phpp\\/caldav\\/calendars\\/Thomas\\/aufgaben\\/) is out of base uri (\\/owncloud\\/remote.php\\/caldav\\/)\",\"Exception\":\"LogicException\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/html\\/3rdparty\\/sabre\\/dav\\/lib\\/DAVACL\\/Plugin.php(756): Sabre\\HTTP\\Request->getPath()\n#1 [internal function]: Sabre\\DAVACL\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \\/var\\/www\\/html\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \\/var\\/www\\/html\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#4 \\/var\\/www\\/html\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/html\\/apps\\/calendar\\/appinfo\\/remote.php(60): Sabre\\DAV\\Server->exec()\n#6 \\/var\\/www\\/html\\/remote.php(137): require_once('\\/var\\/www\\/html\\/a...')\n#7 {main}\",\"File\":\"\\/var\\/www\\/html\\/3rdparty\\/sabre\\/http\\/lib\\/Request.php\",\"Line\":210}","level":4,"time":"2016-01-02T19:03:09+00:00"}

Very strange is the requested uri - it contains remote.phpp with a double p at the end.
The remotAddr 192.168.178.36 is the IP-adress of the nginx reverse proxy.

**Comment by pierreozoux** [comment]
This is the link I put in my thunderbird/lightning, and this is working fine :)

`https://cloud.indie.host/remote.php/caldav/calendars/$username/personal`

Here is my config: https://github.com/indiehosters/ownCloud

**Comment by thomasreus** [comment]
My link in thunderbird is

```
https://<public hostname>/owncloud/remote.php/caldav/calendars/Thomas/aufgaben
```

It's without the double p in "remote.php".

**Comment by lazyfrosch** [comment]
I'm using webdav myself with Enpass (password tool) without a problem. Question is where the double `p` is coming from. Can you access the URL from another webdav client? Like nautilus in Gnome, or the owncloud Desktop client.

**Comment by thomasreus** [comment]
The owncloud desktop clients fails with the same error-message.

**Comment by lazyfrosch** [comment]
So what does your environment for the container look like, do you have a webserver in front?

**Comment by thomasreus** [comment]
I use the offical owncloud container from docker hub (https://hub.docker.com/_/owncloud/) with the tag 'latest' (8.2.2 Apache). I've nothing changed in the container but installing vim for editing config files. Owncloud is configured to use mariadb in another docker container. In the config.php I've added/modified the following entries:

``` php
    'trusted_domains' =>
    array (
        0 => '<fully qualified external hostname of the reverse proxy>,
        1 => '<fully qualified internal hostname of the docker host>',
      ),
    'trusted_proxies'   => ['192.168.178.36'],
    'overwritehost'     => '<fully qualified external hostname of the reverse proxy>',
    'overwriteprotocol' => 'https',
    'overwritewebroot'  => '/owncloud',
    'version' => '8.2.1.4',
    'dbtype' => 'mysql',
    'dbname' => 'owncloud',
    'dbhost' => '<fully qualified internal hostname of the docker host>',
    'dbtableprefix' => 'oc_',
    'dbuser' => 'owncloud',
    'dbpassword' => '<database password>',
```

**Comment by yosifkit** [comment]
(_A shot in the dark_) What happens if you hit it directly from your docker host or another container, without going through the nginx reverse proxy?

**Comment by thomasreus** [comment]
That works as expected. To test that, I have to delete the overwrite_-entries in config.php and connect Thunderbird direct to the exposed port of the docker container on the docker host (via http port 80).
The double p must come from the ownCloud-handling of the overwrite_-parameters.

**Comment by lazyfrosch** [comment]
I guess that the overwrite entries cause problems in WebDAV, what `Requested uri (\\/owncloud\\/remote.phpp\\/caldav\\/calendars\\/Thomas\\/aufgaben\\/) is out of base uri` suggests...

I don't think that is solvable on our side.

**Comment by thomasreus** [comment]
Now I have changed the url from https://<tld>/owncloud to https://<tld> and removed
    'overwritewebroot'  => '/owncloud',
from the config.php. That works, but is not, what I want.
Where can I report that bug, if this side is not the right one?

**Comment by lazyfrosch** [comment]
Well, this is about the Docker integration of owncloud, not the software itself obviously.

The software project is here: https://github.com/owncloud/core

Here is their support page: https://owncloud.org/support/

**Comment by lazyfrosch** [comment]
But still, we don't really support `/owncloud` sub URLs yet, but as it seems there is a mechanism in ownCloud to do so, this seems not to work.

**Comment by thomasreus** [comment]
Thanks. I have opend a new issue:
https://github.com/owncloud/core/issues/21760
