### ISSUE TITLE
Place data directory outside of the web root

### ISSUE THREAD

**Issue by nterray** [docker-library/owncloud#43]
As said in the [upstream documentation](https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/harden_server.html?highlight=security#deployment), data directory should be outside of the Web root.

Is it possible to enable this by default, for example in a dedicated volume?

Best Regards,
Nicolas

**Comment by lazyfrosch** [comment]
You can mount in any volume, and change config.php as you wish.

I believe this is also possible during setup.

**Comment by nterray** [comment]
I didn't see that it was possible to configure it during setup.

Thanks!
