### ISSUE TITLE
Install sudo to be able to use occ script inside

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/owncloud#47]
What do you think about this idea?

If you like, then I PR. I believe it is an important feature.

https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html?highlight=occ#http-user-label

**Comment by yosifkit** [comment]
You need to run `occ` from the same container as the running server?  If so, I think this would work:

``` console
$ docker exec -it --user www-data my-owncloud-container occ status
```

**Comment by pierreozoux** [comment]
Oo! Didn't know this one, thanks!
(But I had another idea in mind also :) https://github.com/docker-library/owncloud/issues/37 )

I close this one then :)

Have a nice day!
