### ISSUE TITLE
Outdated versions for 7.0 and 6.0

### ISSUE THREAD

**Issue by MorrisJobke** [docker-library/owncloud#5]
Have a look at https://owncloud.org/changelog/ for the latest versions.

Currently that are:
- :white_check_mark: 8.1.0
- :white_check_mark: 8.0.5
- :x: 7.0.7
- :x: 6.0.9

Planned releases are time scheduled (https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule) so plan the next one on 2015-08-04 ;)

cc @Moghedrin @tianon

**Comment by LukasReschke** [comment]
Or to phrase it in other words: You released terrible old versions released more than 8 months ago including security bugs. Congrats :tada:

**Comment by daghack** [comment]
Serves me right for not double checking the versions.

**Comment by tianon** [comment]
Thanks for the heads up, @MorrisJobke!  Sorry for the issue!

**Comment by tianon** [comment]
If you've got other notes/suggestions for the image or want to be involved in any capacity, we'd love to have it, btw. :heart:
