### ISSUE TITLE
validate_timestamps redundant

### ISSUE THREAD

**Issue by mbrevda** [docker-library/owncloud#52]
Isn't `opcache.validate_timestamps` redundant in an ephemeral environment? Would it make more sense to disable revalidation totaly?

**Comment by lazyfrosch** [comment]
What comes to my mind is that you can update owncloud addons within the running app, so this would cause problems.

**Comment by lazyfrosch** [comment]
And also the config.php might be affected by this.

**Comment by tianon** [comment]
Indeed, and the image is also useful for development workflows.  I think users who _know_ that their environment is 100% ephemeral should be responsible for updating configuration to account for that (as appropriate for their own individual use case). :+1:

Thanks!
