### ISSUE TITLE
trusted domain error

### ISSUE THREAD

**Issue by zyrill** [docker-library/owncloud#54]
Since updating to OC9, I get a trusted domains misconfiguration error and the owncloud.log reads:
`{"reqId":"f1\/g2mH5ABV0MXzrc+8P","remoteAddr":"172.17.0.1","app":"core","message":"Trusted domain error. \"172.17.0.1\" tried to access using \"myhost.myfritz.net:16443\" as host.","level":2,"time":"2016-03-10T13:26:50+00:00"}`
The relevant part of my config reads:
`'trusted_domains' =>
  array (
    0 => '192.168.66.2:12347',
    1 => 'myhost.myfritz.net:16443',
    2 => '172.17.0.1',
  ),`
Expected behaviour would be not to throw the error at all since I already added the correct domain to the config.

Regarding my setup: I have OC running as a bunch of docker containers (redis, mariadb, oc:fpm and nginx) on an appliance in my home network and the domain myhost.myfritz.net is a dynamic IP resolver. The setup worked just fine with 8.2.2 and I have no idea what I could possibly do to get it working. I should add that I can access the installation when I SSH onto my appliance and use port forwarding just fine. I cannot access my installation when using the local network address *.66.2 neither... Fresh out of ideas what to test or fix.

**Comment by zyrill** [comment]
Am at home now... Access from LAN also not possible:
`{"reqId":"iyZVaczPs9nQGANUKqSh","remoteAddr":"172.17.0.1","app":"core","message":"Trusted domain error. \"172.17.0.1\" tried to access using \"192.168.66.2:12347\" as host.","level":2,"time":"2016-03-10T17:34:56+00:00"}`

**Comment by ghost** [comment]
I had a similar issue. Removing the ports from the trusted domain array fixed it.

**Comment by armandabric** [comment]
> I had a similar issue. Removing the ports from the trusted domain array fixed it.

Me too

**Comment by tianon** [comment]
Closing, as this looks like it's resolved! :+1:
