### ISSUE TITLE
Cannot enable SSL

### ISSUE THREAD

**Issue by strixdio** [docker-library/owncloud#65]
This is probably a pebkac issue, but I cannot get ssl to work in OC9 docker container. I edit the default-ssl.conf and point to my certs (which do work fine with a different apache2 instance), run a2enmod ssl, a2ensite default-ssl, restart the container and it goes into a restart loop. 

`[Thu Mar 17 15:00:10.590320 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_RUN_DIR} is not defined

[Thu Mar 17 15:00:10.590606 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_LOG_DIR} is not defined

[Thu Mar 17 15:00:10.590618 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_LOG_DIR} is not defined

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.74. Set the 'ServerName' directive globally to suppress this message

(2)No such file or directory: AH02291: Cannot access directory '/etc/apache2/${APACHE_LOG_DIR}/' for error log of vhost defined at /etc/apache2/sites-enabled/default-ssl.conf:2

AH00014: Configuration check failed`

What am I doing wrong?

**Comment by yosifkit** [comment]
You probably need to also change the log lines to either use a specific directory or to go to std out like the provided [apache2.conf](https://github.com/docker-library/php/blob/b3678663d8df85a398bd7fc7bdb51d9f3cc93054/5.6/apache/apache2.conf#L51).

**Comment by strixdio** [comment]
When I tried to change the log lines, I get this:

Warning: fopen(/var/www/html/config/config.php): failed to open stream: Permission denied in /var/www/html/lib/private/config.php on line 187

Warning: flock() expects parameter 1 to be resource, boolean given in /var/www/html/lib/private/config.php on line 197

Fatal error: Call to a member function getLogger() on null in /var/www/html/lib/public/util.php on line 166

Will try the apache2.conf, as I didn't realize it was here. Thanks.

**Comment by strixdio** [comment]
I've used the apache2.conf you've specified, getting a reload loop with:

[Thu Mar 17 23:51:00.829775 2016] [core:warn] [pid 1] AH00111: Config variable ${APACHE_RUN_DIR} is not defined

**Comment by tianon** [comment]
I think https://github.com/docker-library/owncloud/issues/23 has a lot of useful dicsussion regarding using this image with SSL. :+1:

**Comment by tianon** [comment]
(As a side note, your issue regarding `APACHE_RUN_DIR` should be fixed with https://github.com/docker-library/php/pull/251.)
