### ISSUE TITLE
Could not execute the `php occ` inside the container

### ISSUE THREAD

**Issue by armandabric** [docker-library/owncloud#67]
To easyly update a config value I want to use the `occ` CLI (see 
https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html#setting-an-array-configuration-value) but as the image do not provide `sudo` it's impossible.

From inside the container:

```
$ php occ
Console has to be executed with the user that owns the file config/config.php
Current user: root
Owner of config.php: www-data
Try adding 'sudo -u www-data ' to the beginning of the command (without the single quotes)

$ sudo
/bin/sh: 3: sudo: not found
```

Own could I use the `occ` CLI with owncloud in a container?

**Comment by pierreozoux** [comment]
easy :)

```
docker exec -it -user www-data my_container bash
```

**Comment by armandabric** [comment]
It's works! :tada: Thanks for the help.

**Comment by martingabelmann** [comment]
or - in your own build - create a script `/usr/bin/occ` (or somewhere else within the PATH) with the following content:

``` bash
#!/bin/bash
su www-data -s /bin/bash -c "php /var/www/html/occ $@"
```

then you can for instance simply run 

``` bash
docker exec oc_container occ upgrade
```

(or even set a `alias occ='docker exec oc_container occ'`)

**Comment by lazyfrosch** [comment]
@martingabelmann could you add this via an PR as `/usr/local/sbin/occ` ?

**Comment by boldt** [comment]
Just for documentation: For me ` docker exec -u www-data -it nextcloud /bin/bash` worked.
