### ISSUE TITLE
can't adjust quota.

### ISSUE THREAD

**Issue by pkahlert** [docker-library/owncloud#71]
Hi,

I can't change the quota for any user.

I'm running the docker on a Mac (Version 10.11.14).
On my HD are 990 GB available and I didn't specify the memory size for the docker.

Maybe anyone can help.

**Comment by yosifkit** [comment]
The user management (and quota) settings are handled through the ownCloud UI:
https://doc.owncloud.org/server/latest/admin_manual/configuration/user/user_configuration.html#setting-storage-quotas

If the options aren't configurable that way I'd imagine something relevant is mounted read-only, maybe a volume/bind-mount or through ownCloud configuration:
https://doc.owncloud.org/server/latest/admin_manual/configuration/server/occ_command.html#files-external-label

Using occ requires being the HTTP user, which is "www-data" so:
```
$ docker exec -itu www-data some-owncloud bash
$ ./occ files_external:list
No admin mounts configured
```

https://github.com/docker-library/docs/tree/master/owncloud#using-occ

**Comment by wglambert** [comment]
Issue seems resolved so going to close
