### ISSUE TITLE
Error trying to create admin user: failed to connect to the database

### ISSUE THREAD

**Issue by arielelkin** [docker-library/owncloud#73]
1. Create a fresh new container with ownCloud: `$ docker run owncloud:9`,
2. Open browser, go to owncloud URL, **Create an admin account**
3. Click "Storage & database", select MySQL/MariaDB
4. Fill in all fields.
5. Click Finish setup.
6. Get error: `Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000][2002] No such file or directory.`

![image](https://cloud.githubusercontent.com/assets/1756909/15802407/7c906c5e-2ab1-11e6-9189-47c3885af1e5.png)

**Comment by tianon** [comment]
Is the `localhost` in that screenshot the value you're using for `host`?  That should be either the name of the MariaDB container in your Docker network, or the name of the linked container's alias (for example, if you used `--link some-maria-container:mysql`, you'd use `mysql` there, not `localhost`).

**Comment by arielelkin** [comment]
I'm a bit confused... [The documentation](https://hub.docker.com/_/owncloud/) for this Dockerfile states that "All data is stored within the default volume `/var/www/html`"

So the Dockerfile can install SQLite but not the other databases?

**Comment by yosifkit** [comment]
> By default this container uses SQLite for data storage, but the wizard should allow for connecting to an existing database.

The "existing database" would be a separate process so it would need to be started up in its own container. Since SQLite is not a separate service that runs a daemon, it can be run "on demand" by the PHP library that uses it.

The defined volume holds the active php code that is Owncloud as well as the uploaded files if I am not mistaken.

**Comment by arielelkin** [comment]
Alright, then that paragraph of the documentation should be updated, because this part of it:

> All data is stored within the default volume /var/www/html`

leads one to believe that all database functionality (e.g. MySQL, PostgreSQL)  is self-contained, when it isn't. 

So given the services and volumes that an ownCloud container requires, how about adding a `docker-compose.yml`?

**Comment by tianon** [comment]
Seems sane!  https://github.com/docker-library/docs/pull/600

**Comment by arielelkin** [comment]
thanks guys, i'll test and get back to you.

**Comment by fayazkk** [comment]
hi all 
i am working on drbd with owncloud.can i am facing the this isssue can any help on this. i migrate the owncloud app and mysql as my wish path  . now app is running but unable to create the admin user. like this error is showing to me. owncloud.log  logs are mention below. 



{"reqId":"WkHbOvvibJoDjWD49MfdSQAAAAQ","remoteAddr":"202.63.215.48","app":"PHP","message":"Class 'PDO' not found at \/mnt\/test\/owncloud\/lib\/private\/setup.php#113","level":3,"time":"2017-12-26T05:16:42+00:00","method":"GET","url":"\/index.php","user":"--"}
