### ISSUE TITLE
is the latest commit pushed to the hub?

### ISSUE THREAD

**Issue by pierreozoux** [docker-library/owncloud#76]
I get a strange error:

```
Pulling app (owncloud:9.0.4-fpm)...
Pulling repository docker.io/library/owncloud
ERROR: Tag 9.0.4-fpm not found in repository docker.io/library/owncloud
```

**Comment by tianon** [comment]
Arg, I think this is https://github.com/docker-library/official-images/issues/1961 rearing its ugly head again; I've prodded the appropriate folks in charge of the signing system to let them know we appear to be missing some tags completely on top of the delays (`docker:1.12.0-rc4*` are missing too).

**Comment by cracker0dks** [comment]
owncloud:9.0.4 still missing but listed in the description :(

**Comment by drubarth** [comment]
maybe update the description until it's fixed so that it's not confusing.
