### ISSUE TITLE
Failed to connect to the database

### ISSUE THREAD

**Issue by k-markov** [docker-library/owncloud#77]
Hi guys,

Using the example "docker-compose.yml" and setting owncloud initial setup as suggested, gives the
following error:
"Error while trying to create admin user:
Failed to connect to the database: An
exception occured in driver:
SQLSTATE[HY000][1045]Access denied 
for user 'root'@'172.17.0.3' (using 
password:YES)

Tried to run containers separately:
% docker run --name some-db -e MYSQL_ROOT_PASSWORD=dbroot -d mariadb
% docker run --name cloud-app -p 8080:80 --link some-db:mysql -d owncloud
but the result is the same.

I believe I'm missing some setting/option/etc., but it is strange that following
exactly the official way of running owncloud container doesn't work.
I'm using docker ver.1.12.0, build 8eab29e and docker-compose version 1.8.0, build f3628c7

Any help is highly appreciated.
-Konstantin

**Comment by tianon** [comment]
Sorry for the huge delay -- this sounds like a case of https://github.com/docker-library/postgres/issues/203#issuecomment-255200501.

I can't reproduce:

```console
$ docker run --name some-db -e MYSQL_ROOT_PASSWORD=dbroot -d mariadb
dad16a902fc9f1803a605aa43b892196d8e5f3ccb7546ecc40109537b65eb00b

$ docker logs --tail=2 some-db
2018-05-07 21:59:47 140699568199552 [Note] mysqld: ready for connections.
Version: '10.2.14-MariaDB-10.2.14+maria~jessie'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

$ docker run --name cloud-app -p 9090:80 --link some-db:mysql -d owncloud
ec0eb5960a8240be323c7f3412bfdf4042649ad8238c4b66a6a4462f35fa721c

$ docker logs cloud-app
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.25. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.25. Set the 'ServerName' directive globally to suppress this message
[Mon May 07 22:00:06.846373 2018] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) PHP/7.0.29 configured -- resuming normal operations
[Mon May 07 22:00:06.846409 2018] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Then I hit http://localhost:9090, expanded "Storage & database", chose "MySQL/MariaDB", and entered the following details:

- Database user: `root`
- Database password: `dbroot`
- Database name: `owncloud`
- Database host: `mysql` (changed from `localhost`)

![image](https://user-images.githubusercontent.com/161631/39727513-cfc8c414-5207-11e8-87f9-19f437e1244f.png)
