### ISSUE TITLE
Cannot access admin web console remotely

### ISSUE THREAD

**Issue by javexed** [docker-library/owncloud#8]
Am using a very basic server to run owncloud
 no gui, and so cannot reach "http://localhost" for the first time run. Found some files in /usr/src/owncloud
Connecting from another box results in:
    You don't have permission to access / on this server.

Not sure if I am doing something wrong.

**Comment by martingabelmann** [comment]
Same problem here, even though with SSH-Tunnel (SOCKS5-Proxy) and then trying with localhost-url it didn`t worked for me.

ps: Apache`s logfiles within container are empty.

**Comment by martingabelmann** [comment]
If i join the container, the html-dir is empty... if i copy the files from `/usr/src/owncloud/` and fix the premissions as in `entrypoint.sh` everything works fine!

 maybe something goes wrong with the if-statement at the start. I guess it would be better to introduce a `mkdir -p /var/www/html` or something like that...

**Comment by javexed** [comment]
Confirmed fixed. Thank you!
