### ISSUE TITLE
No SMB Support

### ISSUE THREAD

**Issue by hemsleyk** [docker-library/owncloud#80]
Since the goal of a container is to do one thing and one thing well, lacking one of the major external storage backends (presumably, one wouldn't want local storage with a container, volume-drivers versus more manageable app-native mounting aside) seems like a major oversight to me. 

SMBClient does add 60MB worth of packages, but I think doing a better job of supporting Windows Server and whitebox NAS products as storage backends in the official base container is worth it, since Owncloud pushes SMB/SAMBA support in their marketing. Submitted a PR for adding to owncloud 9.1 in #79

**Comment by ttufts** [comment]
Bump. Is this being added? I forked and added it, but I'd like to stick to core if I can.

**Comment by tianon** [comment]
See the discussion on #79 -- the question is whether it's really worth the added size, because it is a significant bump.

I'm going to close this issue in favor of keeping the discussion there.
