### ISSUE TITLE
Docker Windows Persistent /var/www/html/data

### ISSUE THREAD

**Issue by vvallee** [docker-library/owncloud#81]
I have large existing media libraries that I would like to have accessible in docker.
I have used below, to do this, which is great, however the owncloud service complains about 0770 permissions. Any ideas?

`owncloud-data:
  volumes:
    - /f/Downloads/MEDIA/DATA:/var/www/html/data/`

**Comment by tianon** [comment]
~~Is this directory shared with a VM using something like `vboxsf`? (Docker Toolbox/`docker-machine`, Docker for Mac, Docker for Windows?)~~

**Comment by tianon** [comment]
Oh sorry, you mentioned Windows already -- yes, this is going to be a constraint of your Windows-based filesystem on `/f/Downloads/MEDIA/DATA`.  Windows does not support the same types of granularity on permissions that Unix does, so I don't think there's much that really can be done here. :disappointed:
