### ISSUE TITLE
Cannot upload large files (2gb+)

### ISSUE THREAD

**Issue by ghost** [docker-library/owncloud#84]
I pulled the latest owncloud docker image.

When uploading large files, at first I kept getting write errors. I later on found out its because the /tmp directory was out of space.

I fixed that by mounting my local directory to /tmp, which gave it a lot more space.

But even after the change, I still couldn't upload my 2gb+ video into owncloud. I was monitoring the /tmp directory to see what's going on there, and noticed the file I'm uploading does seem to go in here (as some random filename), but would stop at around 1.5gb.

I suspect this is some apache configuration issue, but I couldn't find out where. Something is stopping the upload prematurely.

**Comment by tianon** [comment]
Have you looked through https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/big_file_upload_configuration.html to see if any of those settings/tips help? :confused:

**Comment by ghost** [comment]
I did look through that, but I'm not familiar with the web server configuration in this docker container, and was hoping the person that set it up (or someone who is familiar with it) is able to look at this issue and fix it.

**Comment by ghost** [comment]
I played around with the config files for a long time, but without success.

**Comment by dfung-s5a** [comment]
I believe whoever created this image needs to update the apache configs to allow for large file uploads

**Comment by neskweek** [comment]
Same here.
**.user.ini** modifications does not do the trick
The files trigger a download but it's just the _**$DOCKER_PWD/devicemapper/devicemapper/data**_ file that gets growing.
Owncloud just stay stuck on the progress bar saying 'a Few seconds" (I let it  spend the night but no more progress)

**Comment by yosifkit** [comment]
Closing given that this image will no longer be updated.

> This image has been deprecated in favor of the [official `owncloud/server` image](https://hub.docker.com/r/owncloud/server/) provided, maintained, and supported by [ownCloud upstream](https://owncloud.org/download/#owncloud-server-docker). The images found here will receive no further updates after 2018-12-31 (Dec 31, 2018). Please adjust your usage accordingly.
>
> \- https://github.com/docker-library/owncloud/tree/d815707323e2dce4696a1f7b1639f86fc6bf8b8a#deprecated
