### ISSUE TITLE
Advertise `Accept-Ranges`

### ISSUE THREAD

**Issue by recmo** [docker-library/owncloud#86]
The `owncloud:latest` image does not advertise `Accept-Ranges: bytes` in the response headers.

This prevents partial downloads from being resumed and the streaming of media files.

When forced, the server *does* actually support the range requests and handles them correctly, so adding this header to the responses should be sufficient.

**Comment by yosifkit** [comment]
I couldn't find a setting in Apache httpd to unilaterally turn this header on, but this seems related to https://github.com/owncloud/core/issues/21035; I think this [comment](https://github.com/owncloud/core/issues/21035#issuecomment-163018736) is relevant and is probably based off of RFC7233:

> An origin server that supports byte-range requests for a given target
>   resource MAY send
>
>     Accept-Ranges: bytes
>
>   to indicate what range units are supported.  A client MAY generate
>   range requests without having received this header field for the
>   resource involved.
> 
> \- https://tools.ietf.org/html/rfc7233#section-2.3

So servers don't have to say that they accept ranges and clients can try to ask for ranges even while not advertised as such.

**Comment by yosifkit** [comment]
Closing old issue.
