### ISSUE TITLE
Version 9.1.5 is available

### ISSUE THREAD

**Issue by evanp** [docker-library/owncloud#88]
I started getting notifications that 9.1.5 was available from the ownCloud UI.

https://owncloud.org/changelog/#latest9.1

**Comment by yosifkit** [comment]
The Dockerfile was updated in https://github.com/docker-library/owncloud/commit/167aa3b02320358a8cc3cdbbbc3ffb4643d6e369 and pushed to the Docker Hub with https://github.com/docker-library/official-images/pull/2886.

**Comment by agross** [comment]
@yosifkit The notification persists on two of my ownCloud machines. Updated to latest just today.

```sh
$ docker images | grep owncloud
owncloud                       latest              bcb180a7dc19        3 days ago          567 MB

$ docker ps | grep owncloud
7c16b8ce3b95        owncloud                       "/wait-for-it.sh -..."   11 hours ago        Up 11 hours         127.0.0.1:8015->80/tcp      owncloud_owncloud_1

$ docker exec -it -u www-data owncloud_owncloud_1 php occ --version
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
ownCloud version 9.1.4
```

**Comment by yosifkit** [comment]
I think that is explained in https://github.com/docker-library/owncloud/issues/70.

**Comment by agross** [comment]
Thanks, seems I have somehow missed that during (successful) upgrades in the past.
