### ISSUE TITLE
Multiple Vulnerabilities in php 7.0.x

### ISSUE THREAD

**Issue by kujiy** [docker-library/owncloud#90]
Thank you for sharing your excellent product!

php:7.0-apache has vulnerabilities. Could you rebuild the images from php:7.1-apache?

> https://www.cisecurity.org/advisory/multiple-vulnerabilities-in-php-could-allow-for-arbitrary-code-execution/

**Comment by tianon** [comment]
This is similar to https://github.com/docker-library/openjdk/issues/161, https://github.com/docker-library/openjdk/issues/112, https://github.com/docker-library/postgres/issues/286, docker-library/drupal#84, docker-library/official-images#2740, docker-library/ruby#117, docker-library/ruby#94, docker-library/python#152, docker-library/php#242, docker-library/buildpack-deps#46, https://github.com/docker-library/openjdk/issues/185.

The TL;DR is that most of the CVEs reported in these images end up being either false positives or deemed to be of low impact/priority by the Debian security team.  For major security issues, we do automatically rebuild images as promptly as possible.
