### ISSUE TITLE
No releases available for package "pecl.php.net/APCu"

### ISSUE THREAD

**Issue by longquan7** [docker-library/owncloud#92]
I want use this image build on arm64, but when the owncloud/10.0/apache/Dockerfile "RUN pecl install APCu-5.1.8" was install failed. No releases available for package "pecl.php.net/APCu" So I want to know this whether or not arm64 ?

**Comment by tianon** [comment]
Seems to be working OK here! :smile:

https://hub.docker.com/r/arm64v8/owncloud/

**Comment by longquan7** [comment]
@tianon OK,thanks
