### ISSUE TITLE
Data folder permission

### ISSUE THREAD

**Issue by Jobel91** [docker-library/owncloud#95]
Hello, 

I'm using Docker for Windows and I shared volumes, setting up on docker-compose.yml, in order to persist the data.
Extract from my docker-compose.yml

` 
        owncloud:

        image: jobel/owncloud:1.1

        links: 

            - db:db

        ports:

            - 8002:80   

        volumes:

            - f:/Program Files/Docker/Docker VM/owncloudconfig:/var/www/html

            - f:/Program Files/Docker/Docker VM/owncloudconfig/apps:/var/www/html/apps

            - f:/Program Files/Docker/Docker VM/owncloudconfig/config:/var/www/html/config

            - f:/Program Files/Docker/Docker VM/owncloudconfig/data:/var/www/html/data

`

Data are present but when I try to connect on my web browser, it says : "Your data folder  can be read by other users. Please change the directory permissions in 0770 mode so that the content is not listed by other users." (translate fr->eng)

But how can I change the windows folder permissions to 0770 ? ;(

Or what are the others solutions?

Thank you in advance for your answer.

**Comment by tianon** [comment]
Sorry for the delay.  This is actually a quirk of the file sharing driver that Docker has developed for Docker for Windows -- it allows any user full access to all files, but if you check their permissions bits they won't appear to be accessible (which I think is what ownCloud is doing).  Short of patching out that safety check in the ownCloud source, I don't think there's anything we can really do here, sorry! (thus closing the issue)
